<div class="hero-unit span6 offset2">
    <div class="row" style="float:right; padding-bottom:20px">
        <a class="btn btn-primary" href="<?php echo $this->url('instructor/default',array('controller'=>'instructor','action' => 'quizpage','id'=>$lessonId));?>">Ask Question</a>
    </div>

    <div class="row">
        <div id="questions">
        </div>
    </div>
</div>
<div class="row">
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
<script type="text/JavaScript">

function loadLog(){		
	$.ajax({
		url: "../../../../../<?php echo $lessonId;?>log.html",
		cache: false,
		success: function(html){
			$("#questions").html("");		
			$("#questions").html(html); //Insert log into the div								
	  	},
	});
}
setInterval (loadLog, 1000);	//Reload file every 1.0 seconds


/*
function loadLog(){
			var request = new XMLHttpRequest();
			request.open("GET", "../../../../log.xml", false);
			request.send();
			var xml = request.responseXML;
			var users = xml.getElementsByTagName("question");
			$('#chatbox').html("");
			for(var i = 0; i < users.length; i++) {
			    var user = users[i];
			    var names = user.getElementsByTagName("name");
			    for(var j = 0; j < names.length; j++) {
			        //alert(names[j].childNodes[0].nodeValue);
			        $('#chatbox').append(names[j].childNodes[0].nodeValue);
			    }
			}
}
setInterval (loadLog, 2500);	//Reload file every 2.5 seconds
*/
</script>
