<div class="hero-unit span4" style="padding-bottom:20px">

<?php foreach ($quizes as $quiz){?>
    <div class="row">
        <span class="text-info"><?php echo $quiz->name;?></span>
        <button class="form_edit btn btn-info btn-small" id="<?php echo $quiz->form_id;?>">Edit</button>
        <a href="<?php echo $this->url('instructor/default',array('controller'=>'instructor','action' => 'deletequiz','id'=>$quiz->id,'key'=>$quiz->course_section_lesson_id));?>" class="btn btn-info btn-small form-edit">Delete</a>
        <br><br>
    </div>
<?php }?>

<div class="row"><span class="text-info">If additional login required</span><span class="text-warning"> in this page</span><span class="text-info">;<br>Username: onlinequestioning<br>Pass: SSfUfZ20</span></div>

<?php
// Init Form
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

// Configure Errors Helper
$errorsHelper  = $this->plugin('formelementerrors');
$errorsHelper
    ->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>');
?>
<div class="row" style="padding-top:40px">
<?php echo $this->form()->openTag($form); ?>
<fieldset>
    
    <?php
    $elem = $form->get('name');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php echo $errorClass ?>">
        <?php// echo $this->formLabel($elem); ?>
    <div class="controls" style="margin: auto">
            <?php echo $this->formText($elem); ?>
            <?php echo $errorsHelper($elem); ?>
            <button class="btn btn-primary btn-small">Create Quiz</button>
        </div>
    </div>


</fieldset>
<?php echo $this->form()->closeTag($form); ?>
</div></div>
<div class="row"></div>

<script type="text/javascript">
$("input[name='name']").attr("placeholder","Quiz name");
</script>

<script type="text/javascript">
//var $j = jQuery.noConflict();
$(document).ready(function(){ 


JF.initialize({
    enableCookieAuth : true, 
    appName: "Online Questioning",
    accessType: 'full',
    //apiKey:"c890d0436c8066c2a57e3d47904e1e20"
});
$('.form_edit').click(function(e) {
	var formID = $(this).attr('id');
	JF.login(
		    function success() {
		    	JotformAnywhere.editForm(
		    	        formID
		    	    );
	    	    $(this).append(this);
		    },
		    function error() {
		       // $("#loginresults").html("error during authorization");
		    }
		);
});
});
</script>
