<div class="row span12">
  <?php if($settedQuiz):?>
      <div class="hero-unit span6" style="padding:20px; text-align:center"> 
          <h3 class="text-success">
              <?php echo $settedQuiz->name;?>
          </h3>
          <a href="<?php echo $this->url('instructor/default',array('controller'=>'instructor','action' => 'endQuiz','id'=>$settedQuiz->course_section_lesson_id,'key'=>$settedQuiz->id));?>" class="btn btn-danger">End</a>
          <br><br><br>
          <span class="text-success" id="time" style="font-size:34px;"></span>
      </div>
      <script type="text/javascript">
        var myVar=setInterval(function(){myTimer()},1000);
        var i=0;
        var j=0;
        var result;
        function myTimer()
        {
        i++;
        if(i==60)
        {
        	i=0;
        	j++;
        }
        if(i<10)
        	result=j+':0'+i;
        else
        	result=j+':'+i;
        document.getElementById("time").innerHTML=result;
        }
    </script>
  <?php else:?>
      <?php foreach ($quizes as $quiz):?>
         <div class="hero-unit span2" style="padding:20px; text-align:center"> 
              <h3 class="text-info">
                  <?php echo $quiz->name;?>
              </h3>
              <a href="<?php echo $this->url('instructor/default',array('controller'=>'instructor','action' => 'startQuiz','id'=>$quiz->course_section_lesson_id,'key'=>$quiz->id));?>" class="btn btn-primary">Start</a>
          </div>
      <?php endforeach;?>  
  <?php endif;?>
  
</div>
  <?php if ($report):?>
  
  <?php foreach ($report as $chart):?>
  <?php 
//print_r($chart);
//echo count($chart['values']);?>
  <?php if($chart['type']=='control_head'):?>
      
  <?php elseif($chart['type']=='control_radio' ||$chart['type']=='control_dropdown'):?>
  <div class="row span8 offset2" style="margin-top:20px">
      <?php if (isset($chart['values'])):?>
      <?php $d=1;?>
      <img src="../../../../../../bargraph/pie.php?
      <?php foreach ($chart['values'] as $name=>$value):?>
          <?php echo "d".$d."=".$value."&";?>
          <?php echo "t".$d."=".$name."&";?>
          <?php  $d++;?>
          <?php endforeach;?>
          <?php echo "title=".$chart['text'];?>
          <?php echo "&count=".count($chart['values']);?>"
           border=0>
       <?php endif;?>
  </div>
  <?php elseif($chart['type']=='control_checkbox'):?>
    <div class="row span8 offset2" style="margin-top:50px">  
      <?php $d=1;?>
      <img src="../../../../../../bargraph/bar.php?
      <?php foreach ($chart['values'] as $name=>$value):?>
          <?php echo "d".$d."=".$value."&";?>
          <?php echo "t".$d."=".$name."&";?>
          <?php  $d++;?>
          <?php endforeach;?>
          <?php echo "title=".$chart['text'];?>
          <?php echo "&count=".count($chart['values']);?>"
           border=0>
  </div>
  <?php elseif(isset($chart)):?>
      <?php $d=1;?>
      <div class="row span8 offset2" style="margin-top:50px">
      <h2 style="color:#3F5666;"><?php echo $chart['text'];?></h2>
      <table class="table">
          <tr>
              <th>#</th>
              <th>Answer</th>
          </tr>
          <?php if (isset($chart['values'])):?>
          <?php foreach ($chart['values'] as $name=>$value):?>
          <tr>
              <td><?php echo $d;?></td>
              <td><?php echo $value?></td>
          <?php  $d++;?>
          </tr>
          <?php endforeach;?>
          <?php endif;?>
      </table>
      </div>
  <?php endif;?>
  <?php endforeach;?>
      <?php endif;?>

<div class="row">
</div>