<div id="first" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width:auto">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Account Type</h3>
      </div>
      <div class="modal-body">
      <a href="<?php echo $this->url('application/default',array('controller'=>'index','action' => 'makestudent'));?>" class="btn btn-primary btn-large" style="margin:20px">Student</a>
      <a href="<?php echo $this->url('application/default',array('controller'=>'index','action' => 'makeadmin'));?>" class="btn btn-primary btn-large" style="margin:20px">Instructor</a>
      </div>
      <div class="modal-footer">
      </div>
</div>
<script type="text/javascript">
$('#first').modal('show');
$('#first').on('hidden', function () {
	$('#first').modal('show');
	})
</script>