<a href="#askquestion" role="button" class="btn btn-primary" data-toggle="modal">Ask Question</a>
<div id="quiz"></div>
<!-- Modal -->
<div id="askquestion" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Ask Question</h3>
  </div>
  <div class="modal-body">
    <?php
        // Init Form
        $form = $this->askQuestionForm;
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        
        // Configure Errors Helper
        $errorsHelper  = $this->plugin('formelementerrors');
        $errorsHelper
            ->setMessageOpenFormat('<div class="help-block">')
            ->setMessageSeparatorString('</div><div class="help-block">')
            ->setMessageCloseString('</div>');
        ?>
        <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            
            
            <?php
            $elem = $form->get('course_section_lesson_id');
            $elem->setValue($lessonId);
            $elem->setLabelAttributes(array('class' => 'control-label'));
            $errors = $elem->getMessages();
            $errorClass = (!empty($errors)) ? ' error' : '';
            ?>
            <div class="control-group<?php echo $errorClass ?>">
                <div class="controls">
                    <?php echo $this->formHidden($elem); ?>
                    <?php echo $errorsHelper($elem); ?>
                </div>
            </div>
            
            <?php
            $elem = $form->get('name');
            $elem->setLabelAttributes(array('class' => 'control-label'));
            $errors = $elem->getMessages();
            $errorClass = (!empty($errors)) ? ' error' : '';
            ?>
            <div class="control-group<?php echo $errorClass ?>">
            <?php echo $this->formLabel($elem); ?>
                <div class="controls">
                    <?php echo $this->formcheckbox($elem); ?>
                    <?php echo $errorsHelper($elem); ?>
                </div>
            </div>
            
            
            <?php
            $elem = $form->get('value');
            $elem->setLabelAttributes(array('class' => 'control-label'));
            $errors = $elem->getMessages();
            $errorClass = (!empty($errors)) ? ' error' : '';
            ?>
            <div class="control-group<?php echo $errorClass ?>">
                <?php echo $this->formLabel($elem); ?>
                <div class="controls">
                    <?php echo $this->formTextArea($elem); ?>
                    <?php echo $errorsHelper($elem); ?>
                    <button class="btn btn-primary btn-small">Ask</button>
                </div>
            </div>
        
        
        </fieldset>
        <?php echo $this->form()->closeTag($form); ?>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>







<script type="text/javascript">window.handleIFrameMessage = function(e) {var args = e.data.split(":");var iframe = document.getElementById("JotFormIFrame");if (!iframe)return;switch (args[0]) {case "scrollIntoView":iframe.scrollIntoView();break;case "setHeight":iframe.style.height = args[1] + "px";break;}};if (window.addEventListener) {window.addEventListener("message", handleIFrameMessage, false);} else if (window.attachEvent) {window.attachEvent("onmessage", handleIFrameMessage);}</script>


<script type="text/JavaScript">

function loadLog(){
	//$("#quiz").html("");
	
		$.ajax({
			url: "../../../../../<?php echo $lessonId;?>quiz.html",
			cache: false,
			success: function(html){
				if(html==false)
				{
					$("#quiz").html(html); //Insert chat log into the #chatbox div
				}
				if($("#quiz").html()==false)
				{
					$("#quiz").html(html); //Insert chat log into the #chatbox div
				}
		  	},
		  	error:function()
		  	{
		  		$("#quiz").html(""); //Insert chat log into the #chatbox div
			},
		});
	
}
setInterval (loadLog, 1000);
</script>