<div class="hero-unit" style="background-color:rgba(207, 207, 207, 0.23);">
    <?php if(isset($courses)):?>
    <?php foreach ($courses as $c=>$course):?>
    <?php $registered=null;?>
    <?php foreach ($course['sections'] as $r)
    {
        if($r['is_registered'])
              $registered=1;
    }?>
    <?php if(!$registered){?>
        <h4><?php echo $course['code']."  ".$course['name']?></h4>
        <div class="row" style="margin-left:20px">
            <?php foreach ($course['sections'] as $s=>$section):
                    $sno=$s+1;?>
                <h5>
                    <span class="text-info"><?php echo "Section ".$sno;?></span>
                        <a href="<?php echo $this->url('student/default', array('controller'=>'student','action' => 'registersection','id'=>$section['id']));?>" class="btn btn-info btn-mini">Register Section</a>
                </h5>
            <?php endforeach;?>
        </div>
    <?php } else{?>
        <h4><?php echo $course['code']."  ".$course['name']?></h4>
        <div class="row" style="margin-left:20px">
            <?php foreach ($course['sections'] as $s=>$section):
                    $sno=$s+1;?>
                <h5>
                    <?php if($section['is_registered']){?>
                        <?php if($section['is_registered']->is_active){?>
                            <span class="text-success"><?php echo "Section ".$sno;?></span>
                            <a href="" class="btn btn-success btn-mini"  disabled="disabled">Registered</a>
                            <a href="<?php echo $this->url('student/default', array('controller'=>'student','action' => 'unregistersection','id'=>$section['id']));?>" class="btn btn-danger btn-mini">Unregister Section</a>
                        <?php }else {?>
                            <span class="text-warning"><?php echo "Section ".$sno;?></span>
                            <a href="" class="btn btn-warning btn-mini"  disabled="disabled">Waiting for approval</a>
                            <a href="<?php echo $this->url('student/default', array('controller'=>'student','action' => 'unregistersection','id'=>$section['id']));?>" class="btn btn-danger btn-mini">Unregister Section</a>
                        <?php }?>
                    <?php }else {?>
                        <span class="muted"><?php echo "Section ".$sno;?></span>
                    <?php }?>
                </h5>
            <?php endforeach;?>
        </div>
    <?php }?>
    <?php endforeach;?>
    <?php else:?>
    <h3 class="text-warning">There is no course which you can register!</h3>
    <?php endif;?>
</div>