<div class="accordion span8 offset1" id="accordion2">
<?php foreach ($questions as $key=>$question):?>
  <div class="accordion-group">    
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="<?php echo "#".$key;?>">
        <?php echo $question['name'];?>
      </a>
    </div>
    <div id="<?php echo $key;?>" class="accordion-body collapse out">
      <div class="accordion-inner">
      <table class="table table-hover">
      <tr>
          <th>Question</th>
          <th>Answer</th>
      </tr>
        <?php foreach ($question['questions'] as $single):?>
            <tr>
                <td><?php echo $single->value;?></td>
                <td><?php echo $single->answer;?></td>
            </tr>
        <?php endforeach;?>
      </table>
      </div>
    </div>
  </div>
<?php endforeach;?>  
</div>


<div class="row"></div>